config/routes.rb
Proj::Application.routes.draw do
  resources :members

  resources :messages

  get "message/encrypt"
  get "message/decrypt"
  devise_for :users
  resources :masters
  
  

end

app/models/master.rb
class Master < ActiveRecord::Base
  has_secure_password
  #attr_accessible :password,:password_confirmation
#has_secure_password validations: false # This is the key to the solution
#validates :password, presence: true, length: { minimum: 6 } #or whatever you want

end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  before_action :set_master, only: [:show, :edit, :update, :destroy, :encrypt]

  # GET /masters
  # GET /masters.json
  def index
    @masters = Master.all
  end

  # GET /masters/1
  # GET /masters/1.json
  def show
  end
  
  # POST /masters/encrypt
  def encrypt
  @master = Master.new
  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  # POST /masters
  # POST /masters.json
  def create
    @master = Master.new(master_params)

    respond_to do |format|
      if @master.save
        format.html { redirect_to @master, notice: 'Master was successfully created.' }
        format.json { render action: 'show', status: :created, location: @master }
      else
        format.html { render action: 'new' }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1
  # PATCH/PUT /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to @master, notice: 'Master was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1
  # DELETE /masters/1.json
  def destroy
    @master.destroy
    respond_to do |format|
      format.html { redirect_to masters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def master_params
      params.require(:master).permit(:username, :email, :password, :password_confirmation, :publickey, :privatekey)
    end
end

app/helpers/masters_helper.rb
module MastersHelper
end

app/views/masters/_form.html.erb
<%= form_for(@master) do |f| %>
  <% if @master.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@master.errors.count, "error") %> prohibited this master from being saved:</h2>

      <ul>
      <% @master.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :publickey %><br>
    <%= f.text_field :publickey %>
  </div>
  <div class="field">
    <%= f.label :privatekey %><br>
    <%= f.text_field :privatekey %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/masters/edit.html.erb
<h1>Editing master</h1>

<%= render 'form' %>

<%= link_to 'Show', @master %> |
<%= link_to 'Back', masters_path %>

app/views/masters/encrypt.html.erb
<h1>New master</h1>

<%= render 'form' %>

<%= link_to 'Back', masters_path %>

app/views/masters/index.html.erb
<h1>Listing masters</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Publickey</th>
      <th>Privatekey</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @masters.each do |master| %>
      <tr>
        <td><%= master.username %></td>
        <td><%= master.email %></td>
        <td><%= master.publickey %></td>
        <td><%= master.privatekey %></td>
        <td><%= link_to 'Show', master %></td>
        <td><%= link_to 'Edit', edit_master_path(master) %></td>
        <td><%= link_to 'Destroy', master, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Master', new_master_path %>

app/views/masters/new.html.erb
<h1>New master</h1>

<%= render 'form' %>

<%= link_to 'Back', masters_path %>

app/views/masters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @master.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @master.email %>
</p>

<p>
  <strong>Publickey:</strong>
  <%= @master.publickey %>
</p>

<p>
  <strong>Privatekey:</strong>
  <%= @master.privatekey %>
</p>

<%= link_to 'Edit', edit_master_path(@master) %> |
<%= link_to 'Back', masters_path %>